
version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # Mount the current directory to /app for live code reloading
      - .:/app
      # Use a named volume for node_modules to avoid conflicts
      - node_modules:/app/node_modules
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: python main.py
    stdin_open: true
    tty: true

volumes:
  node_modules: